version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: wallet_postgres
    environment:
      POSTGRES_USER: ${DB_USER:-digitalwallet}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-digitalwallet}
      POSTGRES_DB: ${DB_NAME:-digitalwallet}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wallet_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-digitalwallet}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  redis:
    image: redis:7-alpine
    container_name: wallet_redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - wallet_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  app:
    build:
      context: .
    container_name: wallet_api
    ports:
      - "${APP_PORT:-8080}:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - wallet_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  wallet_network:
    driver: bridge